spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wref?useUnicode=true&characterEncoding=utf8
    username: root
    password: mk12kmMK12KMmk12kmMK12KM
  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    baselineOnMigrate: true
    check-location: true
    locations: classpath:db/migration
    schemas: wref
    enabled: true
server:
  port: 8000
timing:
  updateData: 1000
  updateDataTranslate: 60000000000000
  initialDelay: 1
